homeassistant: false
permit_join: true
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://localhost:1883
serial:
  port: /dev/ttyZigbee
advanced:
  network_key: GENERATE
log_level: info
log_output:
  - console
frontend:
  port: 8099
experimental:
  new_api: true
  homeassistant_legacy_entity_attributes: false
  legacy_api: false
  legacy_availability_payload: false
device_options:
  legacy: false
